# Generated by Django 4.2.1 on 2023-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("img", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("mrp", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                (
                    "ratingtotal",
                    models.BigIntegerField(
                        blank=True, db_column="ratingTotal", null=True
                    ),
                ),
                ("discount", models.BigIntegerField(blank=True, null=True)),
                ("seller", models.TextField(blank=True, null=True)),
                ("purl", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("page", models.TextField(blank=True, null=True)),
                ("product_id", models.BigIntegerField(blank=True, null=True)),
                ("sizes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
    ]
