# Generated by Django 4.2.1 on 2023-05-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_products_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="gender",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Girls", "Girls"),
                    ("Boys", "Boys"),
                    ("Unisex", "Unisex"),
                    ("Unisex Kids", "Unisex Kids"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="page",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Clothing-And-Apparels", "Clothing"),
                    ("Accessories", "Accessories"),
                    ("Personal-Care", "Personal Care"),
                    ("Footwear", "Footware"),
                    ("Toys-And-Games", "Toys"),
                    ("Home-Furnishing", "Furnishing"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="seller",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(fields=["category"], name="products_categor_fce6e6_idx"),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(fields=["seller"], name="products_seller_b3ba35_idx"),
        ),
    ]
