# Generated by Django 4.2.1 on 2023-06-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_products_category_alter_products_gender_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="products",
            name="products_categor_fce6e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="products",
            name="products_seller_b3ba35_idx",
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="page",
            field=models.TextField(
                blank=True,
                choices=[
                    ("clothing-and-apparels", "Clothing"),
                    ("accessories", "Accessories"),
                    ("personal-care", "Personal Care"),
                    ("footwear", "Footware"),
                    ("toys-and-games", "Toys"),
                    ("home-furnishing", "Furnishing"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="seller",
            field=models.TextField(blank=True, null=True),
        ),
    ]
