# Generated by Django 4.2.1 on 2023-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_products_products_categor_fce6e6_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="products",
            index=models.Index(
                fields=["seller", "page"], name="products_seller_80f06e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(
                fields=["category", "gender", "page"],
                name="products_categor_c0d328_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(
                fields=["category", "page"], name="products_categor_0c7489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(
                fields=["gender", "page"], name="products_gender_caa16f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="products",
            index=models.Index(fields=["page"], name="products_page_b668b2_idx"),
        ),
    ]
