name: Deploy to Server

on:
  workflow_dispatch:
    inputs:
      enableCodeDeployment:
        description: 'Deploy code'
        required: true
        type: boolean
        default: true
      pipInstall:
        description: 'Pip install'
        required: true
        type: boolean
        default: false
      runMigrations:
        description: 'Run Migrations'
        required: true
        type: boolean
        default: false
      # collectStatic:
      #   description: 'Collect Static'
      #   required: true
      #   type: boolean
      #   default: false

jobs:
  server-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RS_SSH_PRIVATE_KEY }}
          known_hosts: 'github-ecommerce-website-backend-knownhost'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with rsync
        if: ${{ github.event.inputs.enableCodeDeployment == 'true' }}
        run: rsync -avz . ec2-user@${{ secrets.HOST_NAME }}:/home/ec2-user/ecommerce_website/ecommerce_website_backend/

      - name: Pip install
        if: ${{ github.event.inputs.pipInstall == 'true' }}
        run: |
          ssh ec2-user@${{ secrets.HOST_NAME }} \
          'cd /home/ec2-user/ecommerce_website/ecommerce_website_backend/; source ../venv/bin/activate; pip install -r requirements.txt'

      # - name: Collect static
      #   if: ${{ github.event.inputs.collectStatic == 'true' }}
      #   run: |
      #     ssh ec2-user@${{ secrets.HOST_NAME }} \
      #     'cd /home/ec2-user/ecommerce_website/ecommerce_website_backend/; source ../venv/bin/activate; python manage.py collectstatic --noinput'

      - name: Run migrations
        if: ${{ github.event.inputs.runMigrations == 'true' }}
        run: |
          ssh ec2-user@${{ secrets.HOST_NAME }} \
          'cd /home/ec2-user/ecommerce_website/ecommerce_website_backend/; source ../venv/bin/activate; python manage.py migrate'

      - name: Run server
        run: |
          ssh ec2-user@${{ secrets.HOST_NAME }} \
          'cd /home/ec2-user/ecommerce_website/ecommerce_website_backend/; source ../venv/bin/activate; python manage.py runserver 127.0.0.1:8000 &'
